#!/bin/bash

docker rmi -f $(docker images -qa scythe/redis)
docker rmi -f $(docker images -qa scythe/router)
docker rmi -f $(docker images -qa scythe/stserver)
docker rmi -f $(docker images -qa scythe/tmserver)
docker rmi -f $(docker images -qa scythe/viewer)
docker rmi -f $(docker images -qf dangling=true)
